### ISSUE TITLE
DiscordAPIError: Unknown Channel

### ISSUE THREAD

**Issue by Timtaran** [Luxxy-GF/lofibot#1]
```
[INFO] Logged in - MineScale#8791
DiscordAPIError: Unknown Channel
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async ChannelManager.fetch (/home/container/node_modules/discord.js/src/managers/ChannelManager.js:115:18) {
  method: 'get',
  path: '/channels/952266167307894900',
  code: 10003,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}
```

P.S. I set chaneel id `952266167307894884`

**Comment by Timtaran** [comment]
`console.log(952266167307894884)` = `952266167307894900` Lol wtf xD
